"""initial empty migration — proves the Alembic pipeline works

The first migration is intentionally empty (no schema changes yet). Applying it
creates the ``alembic_version`` table in PostgreSQL and marks revision ``0001``
as current, proving that Alembic can connect to the database and run migrations.

Session 3+ will add autogenerated migrations for real tables.

Revision ID: 0001
Revises:
Create Date: 2026-08-10
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
